version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CERTBOT_WWW}:/var/www/certbot:ro
      - ${CERTBOT_CONF_NGINX}:/etc/nginx/ssl:ro
    networks:
      - web
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${CERTBOT_WWW}:/var/www/certbot:rw
      - ${CERTBOT_CONF_NGINX}:/etc/letsencrypt:rw
    networks:
      - web

networks:
  web:
    external: true